name: Check packages

on: [pull_request]

jobs:
  robotcdnjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: download checker
        uses: wei/wget@v1
        with:
          args: https://github.com/cdnjs/tools/releases/latest/download/checker

      - run: sudo chmod +x ./checker

      - name: lint package
        id: lint
        run: |
          mapfile -d '' files < <(
            git diff --name-only -z \
              "${{ github.event.pull_request.base.sha }}" \
              "${{ github.event.pull_request.head.sha }}"
          )
          bash ./scripts/lint.sh "${files[@]}"

      # install glob
      - uses: actions/checkout@v2
        with:
          repository: cdnjs/glob
          path: ./glob
      - run: cd ${{ github.workspace }}/glob && npm install

      - name: compute files
        id: files
        env:
          DOCKER_IMAGE: ghcr.io/cdnjs/tools:cf63aa8265f012629ca4dad9d431f90311d68bcc2
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mapfile -d '' files < <(
            git diff --name-only -z \
              "${{ github.event.pull_request.base.sha }}" \
              "${{ github.event.pull_request.head.sha }}"
          )
          bash ./scripts/show-files.sh "${files[@]}"
